# Configuration for pipeline

# input files and parameters
extended_spike: data/extended_spike.fa
reference_spike: data/reference_spike.fa

# output files
sequential_to_reference: results/sequential_to_reference.csv
